# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=15, null=True)),
                ('race', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
