# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('characters', models.ManyToManyField(blank=True, null=True, to='subject.Character')),
                ('creators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('events', models.ManyToManyField(blank=True, null=True, to='event.Event')),
            ],
        ),
    ]
